### ISSUE TITLE
Support for editing RTTI object fields

### ISSUE THREAD

**Issue by ShadelessFox** [ShadelessFox/decima#11]
The purpose of this tool is not only to show data but also to allow modifying it.

An entire model for editors must be built to support such a feature.

We'll need to figure out a way of tracking our changes. There are some problems:
1. An editor may be "dirty" e.g., contain changes. Since a single editor represents a single core file, we will repack an entire packfile after editing any file and saving it.
2. We could track two different changes levels: the first is packfile-based, and the second one is core file-based (as described in no.1). Then, after editing a core file, we may submit it to the upper level (and maybe store it in some database to allow restarting the application without losing local changes?), and then the packfile could be repacked.

Also, we'll need to figure out a way of repacking data in the first place:
1. We could write all changes to the "patch" packfile
2. We could repack the source packfile (adaptive "in-place" repacking if possible, beware of segmentation)

**Comment by loitranit** [comment]
Hey bro, your project is great. I am in need of a tool that can export text and import text for translation. Fighting

**Comment by ShadelessFox** [comment]
An initial support for replacing contents of files was added. Currently it's only possible to create a separate "patch" file containing changes.

1. Right-click on a desired file in the navigator tree &rArr; `Replace Contents`
2. `File` &rArr; `Save` to persist changes

![java_dynrMJZMJt](https://user-images.githubusercontent.com/35821147/183480521-248d644a-40e8-49fd-b59e-1479028d7bf5.png)
