### ISSUE TITLE
Need help, noob here :)

### ISSUE THREAD

**Issue by nsacerdote** [ShadelessFox/decima#20]
Hi, I'd like to try the tool, but I don't know how to create a project, I'm being asked about paths to some things that I don't know:

![image](https://user-images.githubusercontent.com/12198102/192152476-9a7aa19b-c458-4afe-9c5e-dbfe0bfad4b7.png)

Sorry if this is a stupid question 😄

**Comment by ShadelessFox** [comment]
Hello @nsacerdote,

If you are targeting Horizon Zero Dawn, here's an example of a valid configuration:

![image](https://user-images.githubusercontent.com/35821147/192155227-8545e820-6e7a-48af-9c1a-d14f6e8d0c64.png)

Metadata files can be found here: https://github.com/ShadelessFox/decima/tree/master/data

Please let me know if you have any questions left

**Comment by nsacerdote** [comment]
Great! Yes I was about to post that I got it working:

![image](https://user-images.githubusercontent.com/12198102/192155322-5753eb89-3aa2-46f1-8a50-ada60e0bd5c3.png)

However when I try to load a texture, I get another error:
![image](https://user-images.githubusercontent.com/12198102/192155363-ba74e928-eec7-40fc-97c8-b68fc29ffac6.png)

Not sure if I'm doing something wrong or the texture should be displayed as shown on the readme file

**Comment by REDxEYE** [comment]
I don't think we tested texture support on HZD project, we tested only Death Standing textures

**Comment by REDxEYE** [comment]
Maybe we add support for that today/tomorrow

**Comment by ShadelessFox** [comment]
Texture handling is not supported for HZD.

The error popup was fixed in the master branch, you'll need to build the application yourself

**Comment by nsacerdote** [comment]
Ah I see, perfect, thanks for the info! looks promising! 😄

**Comment by nsacerdote** [comment]
One more question (hopefully last), is there any way to export the files to open it on some hex editor? I don't see the option to extract or export, I only see "Replace with".

**Comment by ShadelessFox** [comment]
Of course! Just drag them from the application to the desktop 🙂

![NVIDIA_Share_4L0ZB3sATy](https://user-images.githubusercontent.com/35821147/192158695-53a6d7bc-c3dd-4b47-8a3e-bc61e5d82ea0.gif)

**Comment by nsacerdote** [comment]
Thanks, I didn't think about that!

**Comment by ShadelessFox** [comment]
I've been thinking of adding such an action in the context menu for a long time, but it was not that important at that moment.

So here it is! You can check it out by pulling changes and rebuilding the application:

![image](https://user-images.githubusercontent.com/35821147/192159575-ee13970e-c70e-41f9-931c-b489b7735902.png)
