### ISSUE TITLE
instructions for how to create a new project

### ISSUE THREAD

**Issue by trickstewart** [ShadelessFox/decima#21]
Please add instructions for creating a new project. I'm able to add executable and Oodle library but am not sure what you mean by game packfile folder path? is that "\DEATH STRANDING DIRECTORS CUT\data"? Also what/where is the RTTl metadata path? I can't find any json in the install. I've also unpacked the entire game with decima without the json file.

**Comment by ShadelessFox** [comment]
Hello @trickstewart,

There are tooltips on some of the fields, I hoped they would help.

Yes, packfile folder patch is `DEATH STRANDING/data` folder.

The metadata files can be found [here](https://github.com/ShadelessFox/decima/tree/master/data), they are shipped with the tool itself. Although they are zipped there, the tool will accept them too. You will need to choose appropriate ones for your game of choice (e.g. for Director's Cut you should use `dsdc` files)

Please let me know if you have any other questions left, I will try me best to help :)

**Comment by ShadelessFox** [comment]
Now the `data` folder is bundled with each release. Hopefully, this change will make it easier to locate these metadata files.

Please see https://github.com/ShadelessFox/decima/releases/tag/v0.1.4
