### ISSUE TITLE
Death Stranding Directors Cut mod issue

### ISSUE THREAD

**Issue by Cyberim** [ShadelessFox/decima#30]
I put the mod in `Death Stranding Directors Cut\data` ,but it doesn't work!

**Comment by ShadelessFox** [comment]
Hello, please provide more context. I'm not a magician, and I can't know everything.

1. What are you referring to as a "mod"?
2. How that "mod" is packaged? Is that a packfile that is supposed to replace an already existing one?
3. Are you sure that "mod" is compatible with the Director's Cut version of the game?

I'd suggest joining our discord channel and continuing our conversation out there. You can find the link in the repo's description.

**Comment by Cyberim** [comment]
> 

what's your discord channel?

and i post here

https://discord.com/channels/744397891073998980/744401865650864138/1055651057855889469

**Comment by ShadelessFox** [comment]
I don't have access to that server.

You can find the link below the `About` block on the repo's main page to the right.
