### ISSUE TITLE
Where is "compressor library" and "type information" located for Horizon Zero Dawn?

### ISSUE THREAD

**Issue by rasitayaz** [ShadelessFox/decima#57]
I'm trying to get into modding Horizon Zero Dawn and come across this application. If there is a comprehensive guide for it, that would also be appreciated. When creating a new project, the program asks for following information:
![image](https://github.com/ShadelessFox/decima/assets/45076094/c21ae499-6d7f-4e3b-8005-5a942d1a5198)
Compressor library asks for a `.so` file and type information asks for a `.json` file. Tried searching for these file extensions in my game directory but couldn't find anything.

**Comment by ShadelessFox** [comment]
Hello @rasitayaz,

The compressor library bundled with HZD is available for Windows only (`.dll`). You'd need to scrap it from any other game that was officially released on Linux. Or you can just ask on our Discord server for help.

Regarding type information, all required files are located under `<app root>/data`.
