### ISSUE TITLE
3D Model viewer not working correctly

### ISSUE THREAD

**Issue by JohnnyDazzling** [ShadelessFox/decima#58]
3D Model viewer not working correctly, no any picture rendered...
![Untitled](https://github.com/ShadelessFox/decima/assets/143889715/5eb8a7b9-4902-4b94-8faa-1b761254db77)

**Comment by ShadelessFox** [comment]
Thanks for the bug report.

As of now, HZD models not really supported.

Will be fixed in the next release.

**Comment by ShadelessFox** [comment]
Fixed in 151903f2d3725006b710504d6489b7dc4f7498b3, you can build manually from the `master` branch or wait for the next release.

I will close the ticket for now. Please let me know if you're experiencing any issues.
