### ISSUE TITLE
.sh file

### ISSUE THREAD

**Issue by Martinligabue** [ShadelessFox/decima#72]
can a .sh file be bundled too for linux?
I tried converting it myself the one in the release, but I'm not sure how to convert the one in the git

https://gist.github.com/Martinligabue/505b4e5a5c3a08717fa15dfb2e9ce6f6

**Comment by REDxEYE** [comment]
There is a shell file, right next to .bat file

**Comment by Martinligabue** [comment]
@REDxEYE ah, I thought it was a binary file. conventionally it should end with .sh
