### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by Cathrine22-june** [ShadelessFox/decima#74]
Hello! All game fonts are in .core file. Can you please tell me how to turn them into .ttfs (or other popular format) and backwards? Thank you very much!

**Comment by ShadelessFox** [comment]
Hi,

You can export fonts as SVG fonts and convert them to any other format using any tool, like FontForge.

Regarding import, it's not possible to achieve using Decima Workshop. Fortunately, there's a standalone tool for that. You can join our Discord server for further help and discussions.
