### ISSUE TITLE
looking for the "green army men figurines"

### ISSUE THREAD

**Issue by ares0027** [ShadelessFox/decima#75]
i aplogize for creating an "issue" for this but this seems to be the only logical place. basically i am trying to export these green army men figurines so i can print them. i think i found their locations but not the actual models. any help/suggestion?

**Comment by ares0027** [comment]
> Hi @ares0027,
> 
> It took me a bit to realize those are literally called _green figures_ in the game files.
> 
> Look for `ds/entities/gimmick/green_figure` using **Edit -> Find Files** or in the navigator inside the **Remainder** archive.

thank you so much for your response. i have actually found those files themselves but they are not 3d model files. when i double click them nothing is shown in model viewer, and model viewer is only available for one. they seem to be json files or something (i am not experienced in this kind of stuff, my apologies, but you can check the screenshot)
![asd](https://github.com/user-attachments/assets/10c6c414-ff41-4e6b-b461-e072d84a7711)
![asd2](https://github.com/user-attachments/assets/a904952c-2a82-413d-b16f-c530f2902ddc)

**Comment by ShadelessFox** [comment]
You shouldn't get any errors when opening that file. At least I don't get it. Please make sure you have **Death Stranding: Director's Cut** selected in your project configuration in case you're working with the DC edition and vice-versa.

**Comment by ares0027** [comment]
> You shouldn't get any errors when opening that file. At least I don't get it. Please make sure you have **Death Stranding: Director's Cut** selected in your project configuration in case you're working with the DC edition and vice-versa.

thank you again for your reply. i actuall own both games on steam but only have director's cut install and selected that one. error i am receiving is this;

`11:28:35.947 INFO  c.s.d.model.packfile.PackfileManager - Mounted 'G:\SteamLibrary\steamapps\common\DEATH STRANDING DIRECTORS CUT\data\c0306eef15c4b5122ab61a834f80d743.bin'
11:28:35.947 INFO  com.shade.decima.model.app.Project - Found and mounted 131 packfiles in 176 ms
11:28:36.579 ERROR c.s.d.m.r.RTTICoreFileReader$LoggingErrorHandlingStrategy - Can't find type with hash 003eaa276eda832a46 in the registry
11:28:36.586 DEBUG c.s.platform.model.ServiceManager - Loading service CoreEditorSettings (CoreEditorSettings)
11:32:29.379 ERROR c.s.d.m.r.RTTICoreFileReader$LoggingErrorHandlingStrategy - Can't find type with hash 003eaa276eda832a46 in the registry
11:32:29.380 ERROR c.s.d.m.r.RTTICoreFileReader$LoggingErrorHandlingStrategy - Can't find type with hash 003eaa276eda832a46 in the registry
11:32:30.145 ERROR c.s.d.m.r.RTTICoreFileReader$LoggingErrorHandlingStrategy - Can't find type with hash 003eaa276eda832a46 in the registry
`

i tried verifying the game, i redownloaded game as a whole to a different ssd but still receiving this error when checking any of army men files. do you have any ideas what i am doing wrong? again, apologies if i am being too much. i just want those models :D

**Comment by REDxEYE** [comment]
When you were configuring project, have you choose DS:DC or just DS? It's very important to choose correct one

**Comment by ares0027** [comment]
> When you were configuring project, have you choose DS:DC or just DS? It's very important to choose correct one

i am a moron, you are right. i did not select anything and default was Death Stranding but i was selecting director's cut exe. it fixed the issue. i can see the models in model viewer with no error now :)


now another follow up if you dont mind: i can export as json or core file (they are a few bytes) but my printer slicer accepts lstl, 3mf, stl, obj, lys, lyt and cws. do you (or anyone really) have any directions for me to export them or modify them into printable models?

**Comment by REDxEYE** [comment]
Give this https://github.com/ShadelessFox/decima/wiki/Model-export wiki page a read, it should explain what you can do with models

**Comment by ShadelessFox** [comment]
Decima Workshop can export models as glTF and our custom format called [DMF](https://github.com/ShadelessFox/decima/wiki/Model-export) with a counterpart importer for blender.

You will most likely need to optimize the models you want to print, but I won't claim that you _should_ because I'm not familiar with that sort of things.

**Comment by ares0027** [comment]
> Give this https://github.com/ShadelessFox/decima/wiki/Model-export wiki page a read, it should explain what you can do with models



> Decima Workshop can export models as glTF and our custom format called [DMF with a counterpart importer for Blender](https://github.com/ShadelessFox/decima/wiki/Model-export).
> 
> You will most likely need to optimize the models you want to print, but I won't claim that you _should_ because I'm not familiar with that sort of things.

thank you both of you, but i can only export as json or core. i installed the plugin properly to blender, tried to save json and core as "*.dmf" but that didnt work and as you can see from the screenshots i cannot export as gITF or DMF, only core or json. it is a supported file as well. what am i doing wrong?

![2024-09-05 13_14_47-Model export · ShadelessFox_decima Wiki](https://github.com/user-attachments/assets/dbe911ce-c9e2-4656-8284-98cb10f68ea8)
![2024-09-05 13_15_08-Decima Workshop - gfet_cto_grfg_def_low core](https://github.com/user-attachments/assets/029a3fc2-0b15-439f-9a15-0abc183ed33e)

**Comment by REDxEYE** [comment]
![image](https://github.com/user-attachments/assets/087667c6-9a4d-4a01-8a53-292fb67836fb)
Export button is in 3d viewer panel

**Comment by ares0027** [comment]
> ![image](https://private-user-images.githubusercontent.com/17544576/364730993-087667c6-9a4d-4a01-8a53-292fb67836fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzE5NDQsIm5iZiI6MTcyNTUzMTY0NCwicGF0aCI6Ii8xNzU0NDU3Ni8zNjQ3MzA5OTMtMDg3NjY3YzYtOWE0ZC00YTAxLThhNTMtMjkyZmI2NzgzNmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDEwMjA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczY2ZmZmZmMWRjNDZhYjQxZTc4M2JmNmMxOTNiYzJkM2MyNzYxNjA4ZWE2MTg1MGNkODFjNDcwYzE2OWM0N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QMN2rp_g8obsZNEbz0u37QnHMzSY9ECYuyEtlQ1EaN0) Export button is in 3d viewer panel

thank you soooo much :) gITF worked much better as you mentioned. dmf showhow showed weird 3d arrows everywhere :)
![2024-09-05 13_24_23-_ (Unsaved) - Blender 4 2 1 LTS](https://github.com/user-attachments/assets/615e22e8-89c1-4810-8b8c-4557ef402b5e)

**Comment by REDxEYE** [comment]
DMF is more designed for map geometry. But it has option for simplified import

**Comment by ShadelessFox** [comment]
Since the issue is resolved, I assume the ticket can be closed now.
